{% set name = "DataLab" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/datalab_platform/datalab_platform-{{ version }}.tar.gz
  sha256: 305aa6b12fb5f196e00c9e74e198be029e0200bf69f7c4b240120492d2999a3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - datalab = datalab.app:run
    - datalab-demo = datalab.tests.scenarios.demo:run
    - datalab-tests = datalab.tests:run
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - guidata >=3.13.4
    - plotpy >=2.8.2
    - sigima >=1.0.6
    - numpy >=1.22,<2.5
    - scipy >=1.10.1,<1.17
    - scikit-image >=0.19.2,<0.27
    - pandas >=1.4,<3.0
    - pywavelets >=1.2,<2.0
    - psutil >=5.8
    - fastapi
    - uvicorn
    - pydantic

test:
  imports:
    - datalab
  commands:
    - pip check
    - QT_QPA_PLATFORM=offscreen pytest --collect-only datalab/tests/
  requires:
    - pip
    - python {{ python_min }}
    - pytest
    - httpx
    - pyqt

about:
  summary: DataLab is a data processing and analysis software for scientific and industrial applications
  home: https://datalab-platform.com/
  description: |
    DataLab is an open-source platform for signal and image processing and visualization for research, education and industry. 
    Leveraging the richness of the scientific Python ecosystem, DataLab is the ideal complement to your data analysis workflows 
    as it can be extended with your Python code through plugins or directly from your IDE or your Jupyter notebooks.
  doc_url: https://datalab-platform.com/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PierreRaybaut
