{% set name = "DataLab" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/datalab_platform/datalab_platform-{{ version }}.tar.gz
  sha256: 8e4517af2c7912f0750371ab83b20db260c348339583257d46b8bb52dd241b85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - datalab = datalab.app:run
    - datalab-demo = datalab.tests.scenarios.demo:run
    - datalab-tests = datalab.tests:run
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - guidata >=3.13.3
    - plotpy >=2.8.2
    - sigima >=1.0.2
    - scipy >=1.10.1
    - scikit-image >=0.19.2
    - opencv >=4.5
    - pandas >=1.4
    - pywavelets >=1.2
    - psutil >=5.8

test:
  imports:
    - datalab
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: DataLab is a data processing and analysis software for scientific and industrial applications
  home: https://datalab-platform.com/
  description: |
    DataLab is an open-source platform for signal and image processing and visualization for research, education and industry. 
    Leveraging the richness of the scientific Python ecosystem, DataLab is the ideal complement to your data analysis workflows 
    as it can be extended with your Python code through plugins or directly from your IDE or your Jupyter notebooks.
  doc_url: https://datalab-platform.com/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PierreRaybaut
