{% set name = "DataLab" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cdl/cdl-{{ version }}.tar.gz
  sha256: 157565dc0bb463b42bdb022db3d74e4c02febc8ca698711c5aee6408fdb3801b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cdl = cdl.app:run
    - datalab = cdl.app:run
    - datalab-demo = cdl.tests.scenarios.demo:run
    - datalab-tests = cdl.tests:run
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - guidata >=3.7
    - plotpy >=2.7
    - scipy >=1.5
    - scikit-image >=0.18
    - opencv >=4.5
    - pandas >=1.2
    - pywavelets >=1.1
    - psutil >=5.7

test:
  imports:
    - cdl
  commands:
    - pip check
  requires:
    - pip

about:
  summary: DataLab (CDL) is a data processing and analysis software for scientific and industrial applications
  home: https://datalab-platform.com/
  description: |
    DataLab is an open-source platform for signal and image processing and visualization for research, education and industry. 
    Leveraging the richness of the scientific Python ecosystem, DataLab is the ideal complement to your data analysis workflows 
    as it can be extended with your Python code through plugins or directly from your IDE or your Jupyter notebooks.
  doc_url: https://datalab-platform.com/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PierreRaybaut
